global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "forge-server"
    static_configs:
      - targets: ["forge-server:9090"]
    metrics_path: /metrics
    scrape_interval: 5s
